location             = "West Europe"
resource_group_name  = "tf_state_store"
storage_account_name = "tfstoragestorestate"
container_name       = "tfstoragecontainertest"
admin_username        = "adminuser"
admin_password        = "Secureme@1234"
vm_name               = "winVM"
# key = ""
