location             = "East US"
resource_group_name  = "tf_rg_state"
storage_account_name = "tfrgststate"
container_name       = "tfrgcontaoner"
admin_username        = "adminuser"
admin_password        = "Secureme@1234"
vm_name               = "winVM"
# key = ""
